### PR TITLE
Upgrade GitHub Actions

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by Stewori** [comment]
The broken tests are not due to this PR. We need to pin pytest to a workable version until we can migrate to current pytest properly...

**Comment by cclauss** [comment]
Perhaps merge #51 first.

**Comment by cclauss** [comment]
Or maybe just remove unused imports. ;-)

**Comment by cclauss** [comment]
Please reapprove the workflow run so we can see the failures.

**Comment by cclauss** [comment]
You gotta love Coveralls...  It fails the tests when `Coverage decreased (-0.0%)`

**Comment by cclauss** [comment]
Looks like the current version of pytest works just fine.

**Comment by Stewori** [comment]
IMHO, we should not use it in MDP. MDP is mostly in maintenance mode, nowadays. Goal is mainly to keep it working with new pythons and stuff (although I would hope to get the cupy backend working eventually). Anyway, no big test-engineering will take place, so Codecov won't be of much help. Did we opt in to it anyway? Or do we have to opt out?

**Comment by cclauss** [comment]
All non-Coveralls tests now pass.

**Comment by Stewori** [comment]
Okay,for simplicity I will accept this now ignoring the coveralls "failures". Thanks for your effort!

**Pull request merged**
