### PR TITLE
OTH: Updated travis.yml to include Python 3.8, NumPy 17.4 and SciKits 22.0.

### PR DESCRIPTION
**Pull request by Stewori**

### CODE REVIEW

**Comment by NiMlr** [comment]
Testing Python 3.8 and scikit-learn 0.20.0, we get an error

```    from .cloudpickle import *
../../../virtualenv/python3.8-dev/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:151: in <module>
    _cell_set_template_code = _make_cell_set_template_code()
../../../virtualenv/python3.8-dev/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:132: in _make_cell_set_template_code
    return types.CodeType(
E   TypeError: an integer is required (got type bytes)```

in
[Python: 3.8-dev, Numpy 1.16.1, scikit-learn 0.20.0](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624814428?utm_medium=notification&utm_source=github_status)
[Python: 3.8-dev, Numpy 1.17.4, scikit-learn 0.20.0](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624814431?utm_medium=notification&utm_source=github_status)
[Python: 3.8, Numpy 1.17.4 scikit-learn 0.20.0](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624814425?utm_medium=notification&utm_source=github_status)
[Python: 3.8, Numpy 1.16.1, scikit-learn 0.20.0](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624814422?utm_medium=notification&utm_source=github_status).

These are all version combinations tested. It seems like cloudpickle [did not work with Python 3.8](https://github.com/cloudpipe/cloudpickle/issues/266). I suggest to leave out the Python 3.8 and scikit-learn 0.20.0 tests.

Maybe it is relevant, that Numpy officially supports Python 3.8 starting in [version in 1.17.4](https://pypi.org/project/numpy/1.17.4/). In an effort to reduce the total number of tests and not having research some problems that may occur in using these combinations when new functionalities are implemented in MDP, we could also drop other tests even if they run now.

**Comment by Stewori** [comment]
Removed the combinations as you suggested. AFAICT the remaining failures should be those described in #62

**Comment by Stewori** [comment]
It appears we have to remove NumPy 1.17.4+SciKits 0.21.3 for Python 3.8.0 as well:
https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/625009786?utm_medium=notification&utm_source=github_status

**Comment by Stewori** [comment]
The only failing tests are now due to #62 which is fixed (but not pushed). For simplicity, I will merge this now and merge the fix for #62 right afterwards.

**Comment by NiMlr** [comment]
> It appears we have to remove NumPy 1.17.4+SciKits 0.21.3 for Python 3.8.0 as well:
> https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/625009786?utm_medium=notification&utm_source=github_status

I agree, [scikit-learn 0.22.0](https://pypi.org/project/scikit-learn/0.21.3/) is the first version to officially support python 3.8. Also see: https://github.com/scikit-learn/scikit-learn/issues/15328

**Comment by Stewori** [comment]
scikts 0.21.3 passes with Python 3.8-dev (presumably 3.8.1) I will keep it for now.

**Pull request merged**
