### PR TITLE
some rudimentary travis setup

### PR DESCRIPTION
**Pull request by yarikoptic**
Let's see if it would work

### CODE REVIEW

**Comment by yarikoptic** [comment]
Please on your end go to travis-ci.org , login through github.com and enable testing on travis for your repo.

Do the same on coveralls.io and codecov.io -- both are used for coverage reporting ;)

**Comment by yarikoptic** [comment]
and it works until getting stuck, see https://travis-ci.org/yarikoptic/mdp-toolkit/builds/114428551

**Comment by pberkes** [comment]
Why was it merged? the run did not succeed

**Comment by otizonaizit** [comment]
to have something to work on. I fixed it already ;)

**Comment by Debilski** [comment]
Piping in some http request does not encourage local testing of the travis file, though.

**Comment by keszybz** [comment]
Wow, not only native Python 3 support but now even CI. Thanks.

**Pull request merged**
